# Artificial Neural Network (ANN)

# Importation des bibliothèques

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

#Part 1 : Data Preprocessing

# Chargemement des données

In [9]:
# x représente les variables indépendantes  qu'on sélectionne à partir de CreditScore
# y -> variable dépendante Exited
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


# Traitement des variables catégorielles

##### Label Encoding de la colonne "Gender"

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [17]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


##### One Hot Encoding pour la colonne "Geography"

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [20]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


##### Diviser le dataset en Training set et Test set

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

##### Standardisation des données

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

#Part 2 - Construction du Réseau de neurone artificiel(ANN)

##### Initialisation du réseau de neurone artificiel

In [31]:
# Création de la variable "ann" qui représente notre réseau de neurone artificiel
ann = tf.keras.models.Sequential()

##### Ajout de la couche d'entrée et de la première couche cachée

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

##### Ajout de la deuxième couche cachée

In [33]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

##### Ajout de la couche de sortie

In [34]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#Part 3 - Entrainer le réseau de neurone artificiel

#####Compiler le réseau de neurone

In [37]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#####Entrainer le réseau de neurone sur le training set

In [38]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5536 - accuracy: 0.7850
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4788 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4519 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4356 - accuracy: 0.7983
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4259 - accuracy: 0.8044
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4192 - accuracy: 0.8055
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4138 - accuracy: 0.8067
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4078 - accuracy: 0.8095
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8081
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3929 - accura

# Part 4 - Prédiction et évaluation du modèle

##### Prédire le résultat d'une seule observation

###### Prédire si le client avec les informations ci-dessous va quitter la banque ou pas:
######Geography: France
######Credit Score: 600
######Gender: Male
######Age: 40 years old
######Tenure: 3 years
######Balance: $ 60000
######Number of Product: 2
######Credit card : yes
######Active Member : yes

######estimatedSalary: $ 50000



In [43]:
# on obtient la probabilité si client reste ou quitte la banque
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
# la probabilité que ce client quitte la banque est de 5%, très faible probabilité
# la proba 0,05 < 0,5 (50% représente le seuil)

[[False]]


##### Prédiction sur le Test

In [44]:
# le vecteur à gauche représente y_pred 
# le vecteur à droite représente y 
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


##### Matrice de confusion

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
# le taux de bonne réponse
accuracy_score(y_test, y_pred)

# on a 1500 bonnes prédictions que le client ne quitte pas la banque
# 211 bonnes prédictions que le client quitte la banque
# 95 false positif -> modèle prédit que ces clients quittent la banque alors que non
# 194 false négatif -> modèle prédit que ces clients ne quittent pas la banque alors que si

[[1500   95]
 [ 194  211]]


0.8555